# Generated by Django 4.2.1 on 2023-06-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipe_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("first", "First"),
                    ("second", "Second"),
                    ("side", "Side"),
                    ("dessert", "Dessert"),
                ],
                default="first",
                max_length=20,
            ),
        ),
    ]
