# Generated by Django 4.2.1 on 2025-01-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_recipe_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="img",
            field=models.ImageField(
                default="media/images/no_image_avilable.png", upload_to="images/"
            ),
        ),
    ]
