# Generated by Django 4.2.1 on 2025-01-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_recipe_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=6)),
                ("unit", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="recipe",
            name="img",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes", to="recipes.ingredient"
            ),
        ),
    ]
