# Generated by Django 4.2.1 on 2025-01-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_alter_recipe_img_remove_recipe_ingredients_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ingredient",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="img",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
