# Generated by Django 4.2.1 on 2025-01-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_delete_ingredient_remove_recipe_ingredients_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="img",
            field=models.ImageField(upload_to="recipes/"),
        ),
    ]
