# Generated by Django 4.2.1 on 2025-02-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_recipe_ingredients_alter_recipe_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="steps",
            field=models.TextField(blank=True, default=""),
        ),
    ]
