# Generated by Django 4.2.1 on 2025-02-02 17:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_recipe_steps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="category",
        ),
        migrations.AddField(
            model_name="recipe",
            name="categories",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Americano", "Americano"),
                    ("Fast-food", "Fast-food"),
                    ("Hamburger", "Hamburger"),
                    ("Asiatico", "Asiatico"),
                    ("Barbecue", "Barbecue"),
                    ("Bevande", "Bevande"),
                    ("Carne", "Carne"),
                    ("Cinese", "Cinese"),
                    ("Colazione", "Colazione"),
                    ("Dessert", "Dessert"),
                    ("Dolci", "Dolci"),
                    ("Frutti di mare", "Frutti di mare"),
                    ("Gelato", "Gelato"),
                    ("Giapponese", "Giapponese"),
                    ("Gourmet", "Gourmet"),
                    ("Greco", "Greco"),
                    ("Indiano", "Indiano"),
                    ("Insalate", "Insalate"),
                    ("Internazionale", "Internazionale"),
                    ("Italiano", "Italiano"),
                    ("Kebab", "Kebab"),
                    ("Latino-americano", "Latino-americano"),
                    ("Libanese", "Libanese"),
                    ("Local food", "Local food"),
                    ("Mediterraneo", "Mediterraneo"),
                    ("Mercati locali", "Mercati locali"),
                    ("Messicano", "Messicano"),
                    ("Panificio e pasticceria", "Panificio e pasticceria"),
                    ("Panini", "Panini"),
                    ("Pasta", "Pasta"),
                    ("Pesce", "Pesce"),
                    ("Piadina", "Piadina"),
                    ("Pizza", "Pizza"),
                    ("Poke", "Poke"),
                    ("Pollo", "Pollo"),
                    ("Sano", "Sano"),
                    ("Senza glutine", "Senza glutine"),
                    ("Snack", "Snack"),
                    ("Sushi", "Sushi"),
                    ("Tè e caffè", "Tè e caffè"),
                    ("Thailandese", "Thailandese"),
                    ("Vegano", "Vegano"),
                    ("Vegetariano", "Vegetariano"),
                ],
                default="Americano",
                max_length=255,
            ),
        ),
    ]
