# Generated by Django 4.2.1 on 2025-02-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_remove_recipe_category_recipe_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="servings",
            field=models.IntegerField(default=1),
        ),
    ]
